# Generated by Django 4.0.1 on 2022-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
    ]
